[package]
name = "urlshortener"
version = "0.1.0"
authors = ["Victor Polevoy <maintainer@vpolevoy.com>"]

description = "A very-very simple url shortener library"
readme = "README.md"
license = "GPL-3.0"
keywords = ["url", "short", "shortenert"]

repository = "https://github.com/vityafx/urlshortener-rs"
documentation = "https://github.com/vityafx/urlshortener-rs"


[dependencies]
hyper = "0.9.9"
