[package]
name = "urlshortener"
version = "0.7.0"
authors = ["Victor Polevoy <maintainer@vpolevoy.com>"]

description = "A very simple url shortener client library"
readme = "README.md"
license = "MIT"
keywords = ["url", "short", "shortener", "link"]

repository = "https://github.com/vityafx/urlshortener-rs"
documentation = "https://vityafx.github.io/urlshortener-rs/master/urlshortener/"

[dependencies]
log = "0.3"
reqwest = "0.7"
url = "1"
